src/Entity/Equipement.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\EquipementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EquipementRepository::class)
 */
class Equipement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_eq;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $desc_eq;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix_eq;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite_eq;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_eq;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="equipements")
     */
    private $category_id;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="equipements",orphanRemoval=true , cascade={"persist"})
     */
    private $images;
    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEq(): ?string
    {
        return $this->nom_eq;
    }

    public function setNomEq(string $nom_eq): self
    {
        $this->nom_eq = $nom_eq;

        return $this;
    }

    public function getDescEq(): ?string
    {
        return $this->desc_eq;
    }

    public function setDescEq(string $desc_eq): self
    {
        $this->desc_eq = $desc_eq;

        return $this;
    }

    public function getPrixEq(): ?int
    {
        return $this->prix_eq;
    }

    public function setPrixEq(int $prix_eq): self
    {
        $this->prix_eq = $prix_eq;

        return $this;
    }

    public function getQuantiteEq(): ?int
    {
        return $this->quantite_eq;
    }

    public function setQuantiteEq(int $quantite_eq): self
    {
        $this->quantite_eq = $quantite_eq;

        return $this;
    }

    public function getImageEq(): ?string
    {
        return $this->image_eq;
    }

    public function setImageEq(string $image_eq): self
    {
        $this->image_eq = $image_eq;

        return $this;
    }

    public function getCategoryId(): ?Categorie
    {
        return $this->category_id;
    }

    public function setCategoryId(?Categorie $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

  /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setEquipements($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAnnonces() === $this) {
                $image->setAnnonces(null);
            }
        }

        return $this;
    }
}

src/Form/EquipementType.php
<?php

namespace App\Form;

use App\Entity\Equipement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;


class EquipementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_eq')
            ->add('desc_eq')
            ->add('prix_eq')
            ->add('quantite_eq')
            ->add('category_id')
            ->add('images', FileType::class, [
                'label' => false,
                'multiple' => true,
                'mapped'=> false,
                'required' =>false
            ])        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Equipement::class,
        ]);
    }
}

src/Controller/EquipementController.php
<?php

namespace App\Controller;

use App\Entity\Equipement;
use App\Entity\Images;

use App\Form\EquipementType;
use App\Repository\EquipementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * @Route("/equipement")
 */
class EquipementController extends AbstractController
{
    
    /**
     * @Route("/affichageaj", name="affichageeqaj", methods={"GET"})
     */
    public function affaj(EquipementRepository $equipementRepository): Response
     {
         return $this->render('equipement/showbackaj.html.twig', [
            'equipements' => $equipementRepository->findAll(),
    ]);

     }

     /**
     * @Route("/liste", name="Equipement_list", methods={"GET"})
     */
    
    public function liste(EquipementRepository $EquipementRepository): Response
    {
       
       
       $pdfOptions = new Options();
       $pdfOptions->set('defaultFont', 'Arial');
       
       // Instantiate Dompdf with our options
       $dompdf = new Dompdf($pdfOptions);
       
       $Equipements = $EquipementRepository->findAll();

       
       // Retrieve the HTML generated in our twig file
       $html = $this->renderView('equipement/liste.html.twig',[
           'equipements'=> $Equipements,
       ]);
       
       // Load HTML to Dompdf
       $dompdf->loadHtml($html);
       
       // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
       $dompdf->setPaper('A4', 'portrait');

       // Render the HTML as PDF
       $dompdf->render();

       // Output the generated PDF to Browser (force download)
       $dompdf->stream("mypdf.pdf", [
           "Attachment" => false
       ]);
   }



     /**
     * @Route("/addeq", name="addeq", methods={"GET"})
     */
    public function affaddeq(EquipementRepository $equipementRepository): Response
    {
        return $this->render('equipement/addeq.html.twig', [
           'equipements' => $equipementRepository->findAll(),
   ]);

    }










    /**
     * @Route("/affichage", name="affichageeq")
     */
    public function aff( Request $request, PaginatorInterface $paginator)
     {

        $donnees = $this->getDoctrine()->getRepository(Equipement::class)->findBy([]);

        $equipements = $paginator->paginate(
            $donnees,
            $request->query->getInt('page', 1),
            4
        );






         return $this->render('equipement/afficherequipement.html.twig', [
            'equipements' => $equipements,

    ]);

     }







    /**
     * @Route("/", name="equipement_index", methods={"GET"})
     */
    public function index(EquipementRepository $equipementRepository): Response
    {
        return $this->render('equipement/index.html.twig', [
            'equipements' => $equipementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="equipement_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $equipement = new Equipement();
        $form = $this->createForm(EquipementType::class, $equipement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) { 
            


            $images = $form->get('images')->getData();
            // Boucle sur les images
            foreach ($images as $image) {
                // on genere un nouveau nom de fichier unique avec md5. guessExtension recupere l'extension du fichier
                $fichier = md5(uniqid()) . '.' . $image->guessExtension();
                //On copie le fichier dans le dossier upload
                $image->move(
                    $this->getParameter('upload_directory'),
                    $fichier
                );

                // on stocke l'image dans la bdd (son nom)
                $img = new Images();
                $img->setName($fichier);
                $equipement->addImage($img);
            }
            $entityManager = $this->getDoctrine()->getManager();





            $entityManager->persist($equipement);
            $entityManager->flush();

            return $this->redirectToRoute('equipement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('equipement/new.html.twig', [
            'equipement' => $equipement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equipement_show", methods={"GET"})
     */
    public function show(Equipement $equipement): Response
    {
        return $this->render('equipement/show.html.twig', [
            'equipement' => $equipement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="equipement_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Equipement $equipement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EquipementType::class, $equipement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('equipement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('equipement/edit.html.twig', [
            'equipement' => $equipement,
            'form' => $form->createView(),
        ]);
    }

    
    /**
     * @Route("/{id}", name="equipement_delete", methods={"POST"})
     */
    public function delete(Request $request, Equipement $equipement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equipement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($equipement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('equipement_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("affeq", name="affeq", methods={"GET"})
     */
    public function afff(EquipementRepository $equipementRepository): Response
    {
        return $this->render('equipement/affeq.html.twig', [
            'equipements' => $equipementRepository->findAll(),
        ]);
    
    }
}

templates/equipement/_delete_form.html.twig
<form method="post" action="{{ path('equipement_delete', {'id': equipement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equipement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/equipement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/equipement/addeq.html.twig
{% extends 'baseBack.html.twig' %}


{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des equipements :</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        <th>name</th>
        <th>description</th>
        <th>prix</th>
        <th>image</th>
        <th>Ajouter</th>
        
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for equipement in equipements %}
        <tr>
            <td> {{ equipement.Id }}</td>
            <td>   {{ equipement.NomEq}}</td>
              <td>   {{ equipement.DescEq }}</td>
              <td>   {{ equipement.PrixEq}}</td>
              <td>   {{ equipement.ImageEq }}</td>
              <td><a href= "{{path('equipement_new',{'id':equipement.Id })}}">Ajouter</a></td>
              
              
             
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
        <th>description</th>
        <th>prix</th>
        <th>image</th>
        <th>Ajouter</th>
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/equipement/affeq.html.twig
{% extends 'baseBack.html.twig' %}


{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des equipements :</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        <th>name</th>
        <th>description</th>
        <th>prix</th>
        <th>image</th>
        
        <th>Modifier</th>
        <th>Supprimer</th>
        <th>Imprimer</th>
      
                
                </tr>
                </thead>
                <tbody>
                


{% for equipement in equipements %}
        <tr>
            <td> {{ equipement.Id }}</td>
            <td>   {{ equipement.NomEq}}</td>
              <td>   {{ equipement.DescEq }}</td>
              <td>   {{ equipement.PrixEq}}</td>
              <td>   {{ equipement.ImageEq }}</td>
              
              <td><a href= "{{path('equipement_edit',{'id':equipement.Id })}}">Modifier</a></td>
              <td><a href= "{{path('equipement_delete',{'id':equipement.Id })}}">Supprimer</a></td>
              
             <td><a href="{{ path('Equipement_list') }}">Imprimer</a></td>
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
        <th>description</th>
        <th>prix</th>
        <th>image</th>
        
        <th>Modifier</th>
        <th>Supprimer</th>
        <th>Imprimer</th>
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/equipement/afficherequipement.html.twig
{% extends 'front_template/front.html.twig' %}


{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
 <link rel="stylesheet" href="{{ asset('unika-front/css/equipement.css') }}">
<section class="content">
       <div class="card-header">
            <h3 class="card-title" style="margin-left : 70px; margin-bottom : 40px ">Listes Des equipements :</h3>
            </div>
  {% for equipement in equipements %}
    <div class="card" style="Display : inline-block">
    {% for image in equipement.images %}
  <img id="image" src="{{ asset ('/uploads/' ~ image.name ) }}" alt=" image" style="width:100%">
  {% endfor %} 
  <h1>{{ equipement.NomEq}}</h1>
  <p class="price">Prix  : {{ equipement.PrixEq}} $</p>
  <p>Description  : {{ equipement.DescEq }}</p>
  <p><button>Commender </button></p>
</div>
    {% endfor %} 


    </section>
    <div style="margin :20px 0 0px 850px " class="pag">
    {{knp_pagination_render(equipements) }}
    </div>
    {% endblock %}








           
           

templates/equipement/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Equipement{% endblock %}

{% block body %}
    <h1>Edit Equipement</h1>

    {{ include('equipement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('equipement_index') }}">back to list</a>

    {{ include('equipement/_delete_form.html.twig') }}
{% endblock %}

templates/equipement/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block body %}
    <h1>Equipement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_eq</th>
                <th>Desc_eq</th>
                <th>Prix_eq</th>
                <th>Quantite_eq</th>
               
                <th>Imprimer</th>
            </tr>
        </thead>
        <tbody>
        {% for equipement in equipements %}
            <tr>
                <td>{{ equipement.id }}</td>
                <td>{{ equipement.nomEq }}</td>
                <td>{{ equipement.descEq }}</td>
                <td>{{ equipement.prixEq }}</td>
                <td>{{ equipement.quantiteEq }}</td>
                
                <td><a href="{{ path('Equipement_list') }}">Imprimer</a></td>
            </tr>
        {% else %}
            
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/equipement/liste.html.twig
{% block body %}
<link rel="stylesheet" href="{{ asset('unika-front/css/pdf.css') }}">
    <h1> Liste des Equipement </h1>
{#}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_eq</th>
                <th>Desc_eq</th>
                <th>Prix_eq</th>
                <th>Quantite_eq</th>
               
            </tr>
        </thead>
        <tbody>
        {% for equipement in equipements %}
            <tr>
                <td>{{ equipement.id }}</td>
                <td>{{ equipement.nomEq }}</td>
                <td>{{ equipement.descEq }}</td>
                <td>{{ equipement.prixEq }}</td>
                <td>{{ equipement.quantiteEq }}</td>
               
                
            </tr>
        {% else %}
            
        {% endfor %}
        </tbody>
    </table>
        
        #}


                <div class="row">
                    <table class="table3 table-condensed table-bordered">
                    <thead>
                        <tr class="head">
                       
                        </tr>
                        <tr>
                        <th class="col1">Id</th>
                        <th class="col2">Nom_eq</th>
                        <th class="col3">Desc_eq</th>
                        <th class="col4">Prix_eq</th>
                        <th class="col5">Quantite_eq</th>
                        
                        </tr>
                    </thead>
                    <tbody>
                        {% for equipement in equipements %}
                        <tr>

                        <td>{{ equipement.id }}</td>
                        <td>{{ equipement.nomEq }}</td>
                        <td>{{ equipement.descEq }}</td>
                        <td>{{ equipement.prixEq }}</td>
                        <td>{{ equipement.quantiteEq }}</td>
               
                      
                        </tr>
                        {% else %}
                        <tr>
                        <td colspan="7"></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                </div>










{% endblock %}

templates/equipement/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}New Equipement{% endblock %}

{% block body %}
    <h1>Create new Equipement</h1>

    {{ include('equipement/_form.html.twig') }}

    <a href="{{ path('equipement_index') }}">back to list</a>
{% endblock %}

templates/equipement/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Equipement{% endblock %}

{% block body %}
    <h1>Equipement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ equipement.id }}</td>
            </tr>
            <tr>
                <th>Nom_eq</th>
                <td>{{ equipement.NomEq }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('equipement_index') }}">back to list</a>

    <a href="{{ path('equipement_edit', {'id': equipement.id}) }}">edit</a>

    {{ include('equipement/_delete_form.html.twig') }}
{% endblock %}