src/Entity/Sponsor.php
<?php

namespace App\Entity;

use App\Repository\SponsorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Routing\Annotation\Route;
/**
 * @ORM\Entity(repositoryClass=SponsorRepository::class)
 */
class Sponsor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")

     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")

     */
    private $nom_sp;

    /**
     * @ORM\Column(type="integer")
     * @Groups("post:read")

     */
    private $num_sp;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")

     */
    private $email_sp;

    /**
     * @ORM\OneToMany(targetEntity=Evenement::class, mappedBy="sponsors_id")
     */
    private $evenements;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSp(): ?string
    {
        return $this->nom_sp;
    }

    public function setNomSp(string $nom_sp): self
    {
        $this->nom_sp = $nom_sp;

        return $this;
    }

    public function getNumSp(): ?int
    {
        return $this->num_sp;
    }

    public function setNumSp(int $num_sp): self
    {
        $this->num_sp = $num_sp;

        return $this;
    }

    public function getEmailSp(): ?string
    {
        return $this->email_sp;
    }

    public function setEmailSp(string $email_sp): self
    {
        $this->email_sp = $email_sp;

        return $this;
    }

    /**
     * @return Collection<int, Evenement>
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setSponsorsId($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            // set the owning side to null (unless already changed)
            if ($evenement->getSponsorsId() === $this) {
                $evenement->setSponsorsId(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
    return (string) $this->getNomSp();
    }
}

src/Form/SponsorType.php
<?php

namespace App\Form;

use App\Entity\Sponsor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SponsorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_sp')
            ->add('num_sp')
            ->add('email_sp')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sponsor::class,
        ]);
    }
}

src/Controller/SponsorController.php
<?php

namespace App\Controller;

use App\Entity\Sponsor;
use App\Form\SponsorType;
use App\Repository\SponsorRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;


/**
 * @Route("/sponsor")
 */
class SponsorController extends AbstractController
{
    
     /**
     * @Route("/", name="sponsor_affichage", methods={"GET"})
     */
    public function affichagee(SponsorRepository $sponsorRepository): Response
    {
        return $this->render('sponsor/affichersponsor.html.twig', [
            'sponsors' => $sponsorRepository->findAll(),
        ]);
    }
      /**
     * @Route("addspon", name="addspon", methods={"GET"})
     */
    public function affichagadspon(SponsorRepository $sponsorRepository): Response
    {
        return $this->render('sponsor/affaddspon.html.twig', [
            'sponsors' => $sponsorRepository->findAll(),
        ]);
    }


      /**
     * @Route("spon", name="spon", methods={"GET"})
     */
    public function aff_spon(SponsorRepository $sponsorRepository): Response
    {
        return $this->render('sponsor/afficherspon.html.twig', [
            'sponsors' => $sponsorRepository->findAll(),
        ]);
    }





    /**
     * @Route("/AllSponsor", name="AllSponsor")
     */
    public function AllSponsor(NormalizerInterface $Normalizer )
    {
    //Nous utilisons la Repository pour récupérer les objets que nous avons dans la base de données
    $repository =$this->getDoctrine()->getRepository(Sponsor::class);
    $sponsors=$repository->FindAll();
    //Nous utilisons la fonction normalize qui transforme en format JSON nos donnée qui sont
    //en tableau d'objet Students
    $jsonContent=$Normalizer->normalize($sponsors,'json',['groups'=>'post:read']);
    
    
    
    return new Response(json_encode($jsonContent));
    dump($jsonContent);
    die;}



















    /**
     * @Route("/", name="sponsor_index", methods={"GET"})
     */
    public function index(SponsorRepository $sponsorRepository): Response
    {
        return $this->render('sponsor/index.html.twig', [
            'sponsors' => $sponsorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="sponsor_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $sponsor = new Sponsor();
        $form = $this->createForm(SponsorType::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($sponsor);
            $entityManager->flush();

            return $this->redirectToRoute('sponsor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('sponsor/new.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sponsor_show", methods={"GET"})
     */
    public function show(Sponsor $sponsor): Response
    {
        return $this->render('sponsor/show.html.twig', [
            'sponsor' => $sponsor,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="sponsor_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Sponsor $sponsor, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SponsorType::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('sponsor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('sponsor/edit.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sponsor_delete", methods={"POST"})
     */
    public function delete(Request $request, Sponsor $sponsor, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sponsor->getId(), $request->request->get('_token'))) {
            $entityManager->remove($sponsor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('sponsor_index', [], Response::HTTP_SEE_OTHER);
    }






    
      /**
     * @Route("/Sponsor/{id}", name="Sponsor/{id}")
     */
    public function Sponsorid(Request $request,$id,NormalizerInterface $Normalizer )
    {
    //Nous utilisons la Repository pour récupérer les objets que nous avons dans la base de données
    $em=$this->getDoctrine()->getManager();
    $sponsors =$em->getRepository(Sponsor::class)->find($id);
    
    //Nous utilisons la fonction normalize qui transforme en format JSON nos donnée qui sont
    //en tableau d'objet Students
    $jsonContent=$Normalizer->normalize($sponsors,'json',['groups'=>'post:read']);
    
 
return new Response(json_encode($jsonContent));

}
    /**
     * @Route("/AddSponsor/new", name="AddSponsor/new")
     */
    public function AddSponsor(Request $request, NormalizerInterface $Normalizer )
    {
    //Nous utilisons la Repository pour récupérer les objets que nous avons dans la base de données
   
    //Nous utilisons la fonction normalize qui transforme en format JSON nos donnée qui sont
    //en tableau d'objet Students
    $em=$this->getDoctrine()->getManager();
    $sponsors=new Sponsor();
    $sponsors-> setNomSp($request->get('nom_sp'));
    
    $sponsors->setNumSp($request->get('num_sp'));
    $sponsors->setEmailSp($request->get('email_sp'));
    $em->persist($sponsors);
    $em->flush();
    $jsonContent=$Normalizer->normalize($sponsors,'json',['groups'=>'post:read']);
    
    return new Response(json_encode($jsonContent));
      
    
   

}





}

templates/sponsor/_delete_form.html.twig
<form method="post" action="{{ path('sponsor_delete', {'id': sponsor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sponsor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sponsor/affaddspon.html.twig
{% extends 'baseBack.html.twig' %}
{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des Sponsors :</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        
        <th>name</th>
        <th>numéro</th>
        <th>email</th>
        
        
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for sponsor in sponsors  %}
        <tr>
            <td> {{  sponsor.id }}</td>
            <td>   {{ sponsor.nomSp }}</td>
             <td>   {{ sponsor.numSp}}</td>
              <td>   {{ sponsor.emailSp }}</td>
              
             
           
              
               
              
            
        </tr>
         
    {%endfor %}

<td><a href="{{path('sponsor_new')}}">ajouter</a></td>
                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
        
        <th>numéro</th>
        <th>email</th>
        
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/sponsor/afficherspon.html.twig
{% extends 'baseBack.html.twig' %}
{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des Sponsors :</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        
        <th>name</th>
        <th>numéro</th>
        <th>email</th>
        <th>supprimer</th>
        <th>modifier</th>
       
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for sponsor in sponsors  %}
        <tr>
            <td> {{  sponsor.id }}</td>
            <td>   {{ sponsor.nomSp }}</td>
             <td>   {{ sponsor.numSp}}</td>
              <td>   {{ sponsor.emailSp }}</td>
              
              <td><a href="{{path('sponsor_delete',{'id': sponsor.id  })}}">Supprimer</a></td>
            <td><a href="{{path('sponsor_edit',{'id': sponsor.id})}}">modifier</a></td>
            
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
        
        <th>numéro</th>
        <th>email</th>
        <th>supprimer</th>
        <th>modifier</th>
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/sponsor/affichersponsor.html.twig
{% extends 'front_template/front.html.twig' %}

{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des Sponsors :</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        
        <th>name</th>
        <th>numéro</th>
        <th>email</th> 
      
                
                </tr>
                </thead>
                <tbody>
                


{% for sponsor in sponsors  %}
        <tr>
            <td> {{  sponsor.id }}</td>
            <td>   {{ sponsor.nomSp }}</td>
             <td>   {{ sponsor.numSp}}</td>
              <td>   {{ sponsor.emailSp }}</td>     
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
        
        <th>numéro</th>
        <th>email</th> 
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/sponsor/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Sponsor{% endblock %}

{% block body %}
    <h1>Edit Sponsor</h1>

    {{ include('sponsor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('sponsor_index') }}">back to list</a>

    {{ include('sponsor/_delete_form.html.twig') }}
{% endblock %}

templates/sponsor/index.html.twig
{% extends 'base.html.twig' %}
{% extends 'baseBack.html.twig' %}
{% block title %}Sponsor index{% endblock %}

{% block body %}
    <h1>Sponsor index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_sp</th>
                <th>Num_sp</th>
                <th>Email_sp</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sponsor in sponsors %}
            <tr>
                <td>{{ sponsor.id }}</td>
                <td>{{ sponsor.nomSp }}</td>
                <td>{{ sponsor.numSp }}</td>
                <td>{{ sponsor.emailSp }}</td>
                <td>
                    <a href="{{ path('sponsor_show', {'id': sponsor.id}) }}">show</a>
                    <a href="{{ path('sponsor_edit', {'id': sponsor.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('sponsor_new') }}">Create new</a>
{% endblock %}

templates/sponsor/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}New Sponsor{% endblock %}

{% block body %}
    <h1>Create new Sponsor</h1>

    {{ include('sponsor/_form.html.twig') }}

    <a href="{{ path('sponsor_index') }}">back to list</a>
{% endblock %}

templates/sponsor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sponsor{% endblock %}

{% block body %}
    <h1>Sponsor</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sponsor.id }}</td>
            </tr>
            <tr>
                <th>Nom_sp</th>
                <td>{{ sponsor.nomSp }}</td>
            </tr>
            <tr>
                <th>Num_sp</th>
                <td>{{ sponsor.numSp }}</td>
            </tr>
            <tr>
                <th>Email_sp</th>
                <td>{{ sponsor.emailSp }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('sponsor_index') }}">back to list</a>

    <a href="{{ path('sponsor_edit', {'id': sponsor.id}) }}">edit</a>

    {{ include('sponsor/_delete_form.html.twig') }}
{% endblock %}