src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_ev;

    /**
     * @ORM\Column(type="date")
     */
    private $date_ev;

    /**
     * @ORM\Column(type="time")
     */
    private $heured_ev;

    /**
     * @ORM\Column(type="time")
     */
    private $heuref_ev;

    /**
     * @ORM\ManyToOne(targetEntity=Sponsor::class, inversedBy="evenements")
     */
    private $sponsors_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEv(): ?string
    {
        return $this->nom_ev;
    }

    public function setNomEv(string $nom_ev): self
    {
        $this->nom_ev = $nom_ev;

        return $this;
    }

    public function getDateEv(): ?\DateTimeInterface
    {
        return $this->date_ev;
    }

    public function setDateEv(\DateTimeInterface $date_ev): self
    {
        $this->date_ev = $date_ev;

        return $this;
    }

    public function getHeuredEv(): ?\DateTimeInterface
    {
        return $this->heured_ev;
    }

    public function setHeuredEv(\DateTimeInterface $heured_ev): self
    {
        $this->heured_ev = $heured_ev;

        return $this;
    }

    public function getHeurefEv(): ?\DateTimeInterface
    {
        return $this->heuref_ev;
    }

    public function setHeurefEv(\DateTimeInterface $heuref_ev): self
    {
        $this->heuref_ev = $heuref_ev;

        return $this;
    }

    public function getSponsorsId(): ?Sponsor
    {
        return $this->sponsors_id;
    }

    public function setSponsorsId(?Sponsor $sponsors_id): self
    {
        $this->sponsors_id = $sponsors_id;

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_ev')
            ->add('date_ev')
            ->add('heured_ev')
            ->add('heuref_ev')
            ->add('sponsors_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * @Route("/evenement")
 */
class EvenementController extends AbstractController
{
    
    /**
     * @Route("/affichage", name="affichage", methods={"GET"})
     */
    public function aff(EvenementRepository $evenementRepository): Response
     {
         return $this->render('evenement/afficherevenement.html.twig', [
            'evenements' => $evenementRepository->findAll(),
    ]);
     }
    /**
     * @Route("/aff_back", name="aff_back", methods={"GET", "POST"})
     */
    public function aff_back(Request $request , EvenementRepository $evenementRepository): Response
     {

        if ( $request->isMethod('POST')){
            if ( $request->request->get('optionsRadios')){
                $trier_cle = $request->request->get('optionsRadios');
                switch($trier_cle){
                    case 'nom':
                        $evennements_triee = $evenementRepository->TrierParNomEvennement();
                        break;

                    case 'date':
                        $evennements_triee = $evenementRepository->TrierParDateEvennement();
                        break;
                }
                return $this->render('evenement/affichercrudevenement.html.twig', [
                    'evenements' => $evennements_triee,
                ]);

            }
        }
        return $this->render('evenement/affichercrudevenement.html.twig', [
            'evenements' => $evenementRepository->findAll(),
    ]);


     }
     /**
     * @Route("/aff_plan", name="aff_plan", methods={"GET"})
     */
    public function aff_plan(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/afficherplanevenement.html.twig', [
           'evenements' => $evenementRepository->findAll(),
   ]);


    }


    /**
     * @Route("/listev", name="evenement_list", methods={"GET"})
     */
    
    public function listev(EvenementRepository $EvenementRepository): Response
     {
        
        
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
        
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        
        $Evenements = $EvenementRepository->findAll();

        
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('evenement/listev.html.twig',[
            'evenements'=> $Evenements,
        ]);
        
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);
    }

    
    
    
    
    /**
     * @Route("/", name="evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="evenement_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="evenement_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_delete", methods={"POST"})
     */
    public function delete(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/affichercrudevenement.html.twig
{% extends 'baseBack.html.twig' %}
{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
              <h3 class="card-title col-9">Listes Des Evenement :</h3>
              <form method="post" style="display:flex">
                  <div class="form-check" style="margin-top:5px;">
                      <label class="form-check-label" style="width: 120px;margin-left: -2px;margin-right: 10px;color: black;">
                      <input type="radio" class="form-check-input" name="optionsRadios" id="nom" value="nom" > nom evennement</label>
                  </div>
                  <div class="form-check" style="margin-top:5px;">
                      <label class="form-check-label" style="width: 120px;margin-left: -2px;margin-right: 10px;color: black;">
                      <input type="radio" class="form-check-input" name="optionsRadios" id="date" value="date" > date evennement </label>
                  </div>
                  <button type="Submit" class="btn btn-success btn-fw">trier</button>
              </form>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        
        <th>Nom</th>
        <th>date</th>
        <th>heure debut</th>
        <th>heure fin</th>
        <th>supprimer</th>
        <th>modifier</th>
        <th>Imprimer</th>
        
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for evenement in evenements  %}
        <tr>
            <td> {{  evenement.id  }}</td>
            <td>   {{ evenement.nomEv}}</td>
             <td>   {{ evenement.dateEv|date('Y-m-d')}}</td>
              <td>   {{ evenement.heuredEv|date('H:i:s') }}</td>
              <td>   {{ evenement.heurefEv|date('H:i:s')  }}</td>
              
              <td><a href="{{path('evenement_delete',{'id': evenement.id  })}}">Supprimer</a></td>
            <td><a href="{{path('evenement_edit',{'id': evenement.id})}}">modifier</a></td>
            <td><a href="{{ path('evenement_list') }}">Imprimer</a></td>
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        
        <th>Nom</th>
        <th>date</th>
        <th>heure debut</th>
        <th>heure fin</th>
        <th>supprimer</th>
        <th>modifier</th>
        <th>Imprimer</th>
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/evenement/afficherevenement.html.twig
{% extends 'front_template/front.html.twig' %}
{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des Evenement :</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        
        <th>Nom</th>
        <th>date</th>
        <th>heure debut</th>
        <th>heure fin</th>
        
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for evenement in evenements  %}
        <tr>
            <td> {{  evenement.id  }}</td>
            <td>   {{ evenement.nomEv}}</td>
             <td>   {{ evenement.dateEv|date('Y-m-d')}}</td>
              <td>   {{ evenement.heuredEv|date('H:i:s') }}</td>
              <td>   {{ evenement.heurefEv|date('H:i:s')  }}</td>
              
            
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
       
        <th>Nom</th>
        <th>date</th>
        <th>heure debut</th>
        <th>heure fin</th>
        
        
                
                </tr>
                </tfoot>
                </table>
  
              </div>
            </div>
          </div>
        </div>
      </div>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/622757a11ffac05b1d7d8e14/1ftkqskbt';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
    </section>
    
    {% endblock %}
    

templates/evenement/afficherplanevenement.html.twig
{% extends 'baseBack.html.twig' %}
{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des Evenement :</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        
        <th>Nom</th>
        <th>date</th>
        <th>heure debut</th>
        <th>heure fin</th>
        
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for evenement in evenements  %}
        <tr>
            <td> {{  evenement.id  }}</td>
            <td>   {{ evenement.nomEv}}</td>
             <td>   {{ evenement.dateEv|date('Y-m-d')}}</td>
              <td>   {{ evenement.heuredEv|date('H:i:s') }}</td>
              <td>   {{ evenement.heurefEv|date('H:i:s')  }}</td>
              
              
            
              
               
              
            
        </tr>
    {%endfor %}
    <td><a href="{{path('evenement_new')}}">ajouter</a></td>


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        
        <th>Nom</th>
        <th>date</th>
        <th>heure debut</th>
        <th>heure fin</th>
        
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/evenement/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}

templates/evenement/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block body %}
    <h1>Evenement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_ev</th>
                <th>Date_ev</th>
                <th>Heured_ev</th>
                <th>Heuref_ev</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.nomEv }}</td>
                <td>{{ evenement.dateEv ? evenement.dateEv|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.heuredEv ? evenement.heuredEv|date('H:i:s') : '' }}</td>
                <td>{{ evenement.heurefEv ? evenement.heurefEv|date('H:i:s') : '' }}</td>
                
            </tr>
        {% else %}
            
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('evenement_new') }}">Create new</a>
    <a href="{{ path('evenement_list') }}">Imprimer</a>
{% endblock %}

templates/evenement/listev.html.twig
{% block body %}
    <h1>Evenement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_ev</th>
                <th>Date_ev</th>
                <th>Heured_ev</th>
                <th>Heuref_ev</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.nomEv }}</td>
                <td>{{ evenement.dateEv ? evenement.dateEv|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.heuredEv ? evenement.heuredEv|date('H:i:s') : '' }}</td>
                <td>{{ evenement.heurefEv ? evenement.heurefEv|date('H:i:s') : '' }}</td>
                
            </tr>
        {% else %}
            
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/evenement/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}New Evenement{% endblock %}

{% block body %}
    <h1>Create new Evenement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('evenement_index') }}">back to list</a>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <h1>Evenement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ evenement.id }}</td>
            </tr>
            <tr>
                <th>Nom_ev</th>
                <td>{{ evenement.nomEv }}</td>
            </tr>
            <tr>
                <th>Date_ev</th>
                <td>{{ evenement.dateEv ? evenement.dateEv|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Heured_ev</th>
                <td>{{ evenement.heuredEv ? evenement.heuredEv|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Heuref_ev</th>
                <td>{{ evenement.heurefEv ? evenement.heurefEv|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('evenement_index') }}">back to list</a>

    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">edit</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}