src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     */
    private $nom_ca;

    /**
     * @ORM\OneToMany(targetEntity=Equipement::class, mappedBy="category_id")
     */
    private $equipements;

    public function __construct()
    {
        $this->equipements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCa(): ?string
    {
        return $this->nom_ca;
    }

    public function setNomCa(string $nom_ca): self
    {
        $this->nom_ca = $nom_ca;

        return $this;
    }

    /**
     * @return Collection<int, Equipement>
     */
    public function getEquipements(): Collection
    {
        return $this->equipements;
    }

    public function addEquipement(Equipement $equipement): self
    {
        if (!$this->equipements->contains($equipement)) {
            $this->equipements[] = $equipement;
            $equipement->setCategoryId($this);
        }

        return $this;
    }

    public function removeEquipement(Equipement $equipement): self
    {
        if ($this->equipements->removeElement($equipement)) {
            // set the owning side to null (unless already changed)
            if ($equipement->getCategoryId() === $this) {
                $equipement->setCategoryId(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
    return (string) $this->getNomCa();
    }
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_ca')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;


/**
 * @Route("/categorie")
 */
class CategorieController extends AbstractController


{




/**
     * @Route("/AllCategorie", name="AllCategorie")
     */
    public function AllCategorie(NormalizerInterface $Normalizer )
    {
    //Nous utilisons la Repository pour récupérer les objets que nous avons dans la base de données
    $repository =$this->getDoctrine()->getRepository(Categorie::class);
    $categories=$repository->FindAll();
    //Nous utilisons la fonction normalize qui transforme en format JSON nos donnée qui sont
    //en tableau d'objet Students
    $jsonContent=$Normalizer->normalize($categories,'json',['groups'=>'post:read']);
    
    
    
    return new Response(json_encode($jsonContent));
    dump($jsonContent);
    die;}
    















      
     /**
     * @Route("/addca", name="addca", methods={"GET"})
     */
    public function addca(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/addca.html.twig', [
           'categories' => $categorieRepository->findAll(),
   ]);

    }

    /**
     * @Route("/affca", name="affca", methods={"GET"})
     */
    public function affca(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/affca.html.twig', [
           'categories' => $categorieRepository->findAll(),
   ]);

    }







      /**
     * @Route("/affichagecategorie", name="affichagecaa", methods={"GET"})
     */
    public function affg(CategorieRepository $categorieRepository): Response
     {
         return $this->render('categorie/showbackc.html.twig', [
            'categories' => $categorieRepository->findAll(),
    ]);

     }
    /**
     * @Route("/affichage", name="affichageca", methods={"GET"})
     */
    public function aff(CategorieRepository $categorieRepository): Response
     {
         return $this->render('categorie/affichercategorie.html.twig', [
            'categories' => $categorieRepository->findAll(),
    ]);

     }
    /**
     * @Route("/", name="categorie_index", methods={"GET"})
     */
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="categorie_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($categorie);
            $entityManager->flush();

            return $this->redirectToRoute('categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categorie_show", methods={"GET"})
     */
    public function show(Categorie $categorie): Response
    {
        return $this->render('categorie/show.html.twig', [
            'categorie' => $categorie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="categorie_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Categorie $categorie, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categorie/edit.html.twig', [
            'categorie' => $categorie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categorie_delete", methods={"POST"})
     */
    public function delete(Request $request, Categorie $categorie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categorie->getId(), $request->request->get('_token'))) {
            $entityManager->remove($categorie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('categorie_index', [], Response::HTTP_SEE_OTHER);
    }
























      /**
     * @Route("/Categorie/{id}", name="Categorie/{id}")
     */
    public function Categorieid(Request $request,$id,NormalizerInterface $Normalizer )
    {
    //Nous utilisons la Repository pour récupérer les objets que nous avons dans la base de données
    $em=$this->getDoctrine()->getManager();
    $categories =$em->getRepository(Categorie::class)->find($id);
    
    //Nous utilisons la fonction normalize qui transforme en format JSON nos donnée qui sont
    //en tableau d'objet Students
    $jsonContent=$Normalizer->normalize($categories,'json',['groups'=>'post:read']);
    
 
return new Response(json_encode($jsonContent));

}
    /**
     * @Route("/AddCategorie/new", name="AddCategorie/new")
     */
    public function AddCategorie(Request $request, NormalizerInterface $Normalizer )
    {
    //Nous utilisons la Repository pour récupérer les objets que nous avons dans la base de données
   
    //Nous utilisons la fonction normalize qui transforme en format JSON nos donnée qui sont
    //en tableau d'objet Students
    $em=$this->getDoctrine()->getManager();
    $categories=new Categorie();
    $categories->setNomCa($request->get('nom_ca'));
    
    $em->persist($categories);
    $em->flush();
    $jsonContent=$Normalizer->normalize($categories,'json',['groups'=>'post:read']);
    
    return new Response(json_encode($jsonContent));
      
    
   

}















  
}

templates/categorie/_delete_form.html.twig
<form method="post" action="{{ path('categorie_delete', {'id': categorie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categorie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/categorie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/categorie/addca.html.twig
{% extends 'baseBack.html.twig' %}

{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des catégorie:</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        <th>name</th>
        <th>Ajouter</th>
    
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for categorie in categories  %}
        <tr>
            <td> {{ categorie.Id }}</td>
            <td>   {{ categorie.NomCa}}</td>
            <td><a href= "{{path('categorie_new',{'id':categorie.Id })}}">Ajouter</a></td>
        
              
             
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
        <th>Ajouter</th>
      
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/categorie/affca.html.twig
{% extends 'baseBack.html.twig' %}

{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des catégorie:</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        <th>name</th>
        
        <th>Modifier</th>
        <th>Supprimer</th>
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for categorie in categories  %}
        <tr>
            <td> {{ categorie.Id }}</td>
            <td>   {{ categorie.NomCa}}</td>
            
            <td><a href= "{{path('categorie_edit',{'id':categorie.Id })}}">Modifier</a></td>
            <td><a href= "{{path('categorie_delete',{'id':categorie.Id })}}">Supprimer</a></td>
              
             
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
       
        <th>Modifier</th>
        <th>Supprimer</th>
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/categorie/affichercategorie.html.twig
{% extends 'front_template/front.html.twig' %}

{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">

{% endblock %}
{% block body %}
<link rel="stylesheet" href="{{ asset('unika-front/css/e.css') }}">
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des catégorie:</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                
        <th>nom de categorie</th>
        
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for categorie in categories  %}
        <tr>
           
            <td>   {{ categorie.NomCa}}</td>
              
              
             
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
              
        <th>nom de categorie</th>
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

templates/categorie/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Categorie{% endblock %}

{% block body %}
    <h1>Edit Categorie</h1>

    {{ include('categorie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('categorie_index') }}">back to list</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}

templates/categorie/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Categorie index{% endblock %}

{% block body %}
    <h1>Categorie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_ca</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for categorie in categories %}
            <tr>
                <td>{{ categorie.id }}</td>
                <td>{{ categorie.nomCa }}</td>
                <td>
                    <a href="{{ path('categorie_show', {'id': categorie.id}) }}">show</a>
                    <a href="{{ path('categorie_edit', {'id': categorie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('categorie_new') }}">Create new</a>
{% endblock %}

templates/categorie/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}New Categorie{% endblock %}

{% block body %}
    <h1>Create new Categorie</h1>

    {{ include('categorie/_form.html.twig') }}

    <a href="{{ path('categorie_index') }}">back to list</a>
{% endblock %}

templates/categorie/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ categorie.id }}</td>
            </tr>
            <tr>
                <th>Nom_ca</th>
                <td>{{ categorie.nomCa }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('categorie_index') }}">back to list</a>

    <a href="{{ path('categorie_edit', {'id': categorie.id}) }}">edit</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}

templates/categorie/showbackc.html.twig
{% extends 'baseBack.html.twig' %}

{% block javascripts %}
<script src="{{ asset('../back-office/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/pdfmake/vfs_fonts.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('../back-office/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
<script>
$(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
});
  </script>
{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('back-office/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('back-office/dist/css/adminlte.min.css') }}">
{% endblock %}
{% block body %}
<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
            <div class="card-header">
            <h3 class="card-title">Listes Des catégorie:</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                <th>id</th>
        <th>name</th>
        
        <th>Modefier</th>
        <th>Supprimer</th>
        
      
                
                </tr>
                </thead>
                <tbody>
                


{% for categorie in categories  %}
        <tr>
            <td> {{ categorie.Id }}</td>
            <td>   {{ categorie.NomCa}}</td>
            
            <td><a href= "{{path('categorie_edit',{'id':categorie.Id })}}">Modefier</a></td>
            <td><a href= "{{path('categorie_delete',{'id':categorie.Id })}}">Supprimer</a></td>
              
             
              
               
              
            
        </tr>
    {%endfor %}


                </tbody>
                <tfoot>
                <tr>
               <th>id</th>
        <th>name</th>
       
        <th>Modefier</th>
        <th>Supprimer</th>
        
        
                
                </tr>
                </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}